#!/bin/bash
#SBATCH -p shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=2G
#SBATCH -t 10:00:00
#SBATCH -J MAGEPROsubmit
#SBATCH -A csd832
#SBATCH -o ../../working_err/MAGEPROsubmit.%j.%N.out
#SBATCH -e ../../working_err/MAGEPROsubmit.%j.%N.err
#SBATCH --export=ALL
#SBATCH --constraint="lustre"

source ~/.bashrc
conda activate r_py

Rscript RUN_GENE_MODEL_TEST.R --bfile /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/genotypes/consents_combined/AA/maf_hwe_rate_filtered_HM3_filtered/downsampled/MESA_AAchr --ge /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/gene_expression/processed/MESA_AA_ge_normalized.bed.gz --covar /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/covars/ready/MESA_AA_covariates.txt --out /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_HIS_Monocyte_APPLY_AA/weights_ds --scratch /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_HIS_Monocyte_APPLY_AA/scratch_ds --intermed_dir /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_HIS_Monocyte_APPLY_AA/intermediate_ds --PATH_plink /expanse/lustre/projects/ddp412/kakamatsu/plink --PATH_gcta /expanse/lustre/projects/ddp412/kakamatsu/fusion_twas-master/gcta_nr_robust --rerun FALSE --hsq_p 1 --verbose 2 --genemodel /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_HIS_Monocyte/weights_for_crossanc --insample_bim /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_HIS_Monocyte/scratch_ds/plink_gene --num_covar 42

Rscript RUN_GENE_MODEL_TEST.R --bfile /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/genotypes/consents_combined/AA/maf_hwe_rate_filtered_HM3_filtered/downsampled/MESA_AAchr --ge /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/gene_expression/processed/MESA_AA_ge_normalized.bed.gz --covar /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/covars/ready/MESA_AA_covariates.txt --out /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_CAU_Monocyte_APPLY_AA/weights_ds--scratch /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_CAU_Monocyte_APPLY_AA/scratch_ds --intermed_dir /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_CAU_Monocyte_APPLY_AA/intermediate_ds --PATH_plink /expanse/lustre/projects/ddp412/kakamatsu/plink --PATH_gcta /expanse/lustre/projects/ddp412/kakamatsu/fusion_twas-master/gcta_nr_robust --rerun FALSE --hsq_p 1 --verbose 2 --genemodel /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_CAU_Monocyte/weights_for_crossanc --insample_bim /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_CAU_Monocyte/scratch_ds/plink_gene --num_covar 42

Rscript RUN_GENE_MODEL_TEST.R --bfile /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/genotypes/consents_combined/HIS/maf_hwe_rate_filtered_HM3_filtered/downsampled/MESA_HISchr --ge /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/gene_expression/processed/MESA_HIS_ge_normalized.bed.gz --covar /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/covars/ready/MESA_HIS_covariates.txt --out /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_AA_Monocyte_APPLY_HIS/weights_ds --scratch /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_AA_Monocyte_APPLY_HIS/scratch_ds --intermed_dir /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_AA_Monocyte_APPLY_HIS/intermediate_ds --PATH_plink /expanse/lustre/projects/ddp412/kakamatsu/plink --PATH_gcta /expanse/lustre/projects/ddp412/kakamatsu/fusion_twas-master/gcta_nr_robust --rerun FALSE --hsq_p 1 --verbose 2 --genemodel /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_AA_Monocyte/weights_for_crossanc --insample_bim /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_AA_Monocyte/scratch_ds/plink_gene --num_covar 42

Rscript RUN_GENE_MODEL_TEST.R --bfile /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/genotypes/consents_combined/HIS/maf_hwe_rate_filtered_HM3_filtered/downsampled/MESA_HISchr --ge /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/gene_expression/processed/MESA_HIS_ge_normalized.bed.gz --covar /expanse/lustre/projects/ddp412/kakamatsu/GENOTYPES_GE_data/MESA/covars/ready/MESA_HIS_covariates.txt --out /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_CAU_Monocyte_APPLY_HIS/weights_ds --scratch /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_CAU_Monocyte_APPLY_HIS/scratch_ds --intermed_dir /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_CAU_Monocyte_APPLY_HIS/intermediate_ds --PATH_plink /expanse/lustre/projects/ddp412/kakamatsu/plink --PATH_gcta /expanse/lustre/projects/ddp412/kakamatsu/fusion_twas-master/gcta_nr_robust --rerun FALSE --hsq_p 1 --verbose 2 --genemodel /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_CAU_Monocyte/weights_for_crossanc --insample_bim /expanse/lustre/projects/ddp412/kakamatsu/GENE_MODELS/MESA_CAU_Monocyte/scratch_ds/plink_gene --num_covar 42
